# -*- coding: utf-8 -*-
"""Copy of Customer_Segmentation_and _Churn_Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16W7GbmNjPLw8Lc3R4oYRon6aJ3qdhTZg
"""

import pandas as pd
from google.colab import files
uploaddes = files.upload()

df = pd.read_csv(next(iter(uploaddes)))

df.head()

df.shape
df.info
df.isnull().sum()
df.duplicated().sum()
df.describe()

# Remove duplicate rows
df = df.drop_duplicates()
# check duplicate rows after removing
df.duplicated().sum()

#check unique values in categorical columns
print(df['Geography'].unique())
print(df['Gender'].unique())
print(df['Exited'].unique())

#summary of categorical columns
df[['Geography','Gender','Exited']].describe()

import matplotlib.pyplot as plt
print("Matplotlib Imported")

import seaborn as sns
print("Seaborn Imported")

sns.countplot(df['Exited'])
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(x='Exited', data=df)
plt .title("customer Churn Distribution")
plt.show()

plt.figure(figsize=(7,5))
sns.countplot(x='Geography',
hue='Exited', data=df)
plt.title("Geography vs Customer Churn")
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(x='Gender',
hue='Exited', data=df)
plt.title("Gender vs Customer Churn")
plt.show()

plt.figure(figsize=(7,5))
sns.histplot(df['Age'], bins=30,
kde=True)
plt.title("Age Distribution of Customers")
plt.show()

plt.figure(figsize=(7,5))
sns.histplot(df['Age'],bins=30,
kde=True)
plt.title("Credit Score Distribution")
plt.show()

plt.figure(figsize=(7,5))
sns.histplot(df['Balance'],bins=30,
kde=True)
plt.title("Balance Distribution")
plt.show()

plt.figure(figsize=(10,8))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

df.groupby("Geography")["Balance"].mean()

df.groupby("Gender")["EstimatedSalary"].mean()

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

X = df[['CreditScore','Age','Balance','EstimatedSalary']]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

wcss = []

for i in range(1,11):
    kmeans = KMeans(n_clusters=i, random_state=42, n_init=10)
    kmeans.fit(X_scaled)
    wcss.append(kmeans.inertia_)

plt.figure(figsize=(7,5))
plt.plot(range(1,11), wcss, marker='o')
plt.title("Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
plt.show()

kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
df['Cluster'] = kmeans.fit_predict(X_scaled)

df['Cluster'].value_counts()

plt.figure(figsize=(8,6))
sns.scatterplot(
    data=df,
    x='Age',
    y='Balance',
    hue='Cluster',
    palette='Set2'
)
plt.title("Customer Segmentation using K-Means")
plt.show()

kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
df['Cluster'] = kmeans.fit_predict(X_scaled)

df['Cluster'].value_counts()

plt.figure(figsize=(8,6))
sns.scatterplot(
    data=df,
    x='Age',
    y='Balance',
    hue='Cluster',
    palette='Set2'
)
plt.title("Customer Segmentation using K-Means")
plt.xlabel("Age")
plt.ylabel("Balance")
plt.show()

df.groupby('Cluster')[['Age','Balance','EstimatedSalary','CreditScore']].mean()

X = df.drop(['Exited', 'Cluster'], axis=1)
y = df['Exited']

X = pd.get_dummies(X, drop_first=True)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

import pandas as pd

feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': model.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by='Importance',
    ascending=False
)

feature_importance.head(10)

plt.figure(figsize=(8,6))
sns.barplot(
    data=feature_importance.head(10),
    x='Importance',
    y='Feature'
)
plt.title("Top 10 Important Features")
plt.show()

from sklearn.metrics import roc_curve, auc

y_prob = model.predict_proba(X_test)[:,1]

fpr, tpr, thresholds = roc_curve(y_test, y_prob)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label='ROC Curve (AUC = %0.2f)' % roc_auc)
plt.plot([0,1],[0,1],'r--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend()
plt.show()

"""# Business Insights

- Customers with low credit scores have a higher churn risk.
- Middle-aged customers show higher churn than younger customers.
- Geography significantly affects customer churn.
- Customers with higher balances are more likely to churn.
- Estimated salary has a moderate impact on churn.
- Customer segmentation helps identify different customer groups.
- Personalized offers can improve customer retention.
- Loyalty programs can reduce customer churn.
- Predictive analytics helps identify at-risk customers early.
- Data-driven decisions can improve customer satisfaction and profitability.

# Conclusion

This project analyzed customer segmentation and churn patterns in European banking using data analysis, visualization, K-Means clustering, and Random Forest classification. The results identified important factors influencing customer churn and provided valuable business recommendations for improving customer retention
"""